# Generated by Django 2.0 on 2020-01-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hostinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hostname', models.CharField(max_length=20)),
                ('Ip', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
                ('Cpu', models.CharField(max_length=20)),
                ('Mem', models.CharField(max_length=20)),
                ('Disk', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Hostinfo',
            },
        ),
        migrations.CreateModel(
            name='Loginfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Messages', models.CharField(max_length=20)),
                ('Time', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Loginfo',
            },
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('User', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
                ('Mobile', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Userinfo',
            },
        ),
    ]
