# Generated by Django 2.0 on 2020-01-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0002_auto_20200118_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='Name',
            field=models.CharField(max_length=20, unique=True, verbose_name='机房名称'),
        ),
    ]
