# Generated by Django 2.0 on 2020-01-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0003_auto_20200118_1107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hostinfo',
            options={'verbose_name': '主机信息', 'verbose_name_plural': '主机信息'},
        ),
        migrations.AlterModelOptions(
            name='loginfo',
            options={'verbose_name': '日志信息', 'verbose_name_plural': '日志信息'},
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='Date',
            field=models.DateField(auto_now=True, max_length=20, verbose_name='最后修改时间'),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='Cpu',
            field=models.CharField(max_length=20, verbose_name='CPU'),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='Disk',
            field=models.CharField(max_length=20, verbose_name='磁盘'),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='Hostname',
            field=models.CharField(max_length=20, verbose_name='主机名'),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='Ip',
            field=models.CharField(max_length=20, verbose_name='ip地址'),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='Mem',
            field=models.CharField(max_length=20, verbose_name='内存'),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='Password',
            field=models.CharField(max_length=20, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='loginfo',
            name='Messages',
            field=models.CharField(max_length=20, verbose_name='消息'),
        ),
        migrations.AlterField(
            model_name='loginfo',
            name='Time',
            field=models.CharField(max_length=20, verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='Email',
            field=models.CharField(max_length=20, verbose_name='邮件'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='Mobile',
            field=models.CharField(max_length=20, verbose_name='手机'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='Name',
            field=models.CharField(max_length=20, unique=True, verbose_name='名字'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='Password',
            field=models.CharField(max_length=20, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='User',
            field=models.CharField(max_length=20, verbose_name='用户'),
        ),
    ]
