# Generated by Django 2.0 on 2020-01-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0005_auto_20200118_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostinfo',
            name='Date',
            field=models.DateTimeField(auto_now=True, verbose_name='最后修改时间'),
        ),
    ]
