# Generated by Django 2.0 on 2020-01-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0006_auto_20200118_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostinfo',
            name='Date',
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='Time',
            field=models.DateTimeField(auto_now=True, verbose_name='时间'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='Time',
            field=models.DateTimeField(auto_now=True, verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='loginfo',
            name='Time',
            field=models.DateTimeField(auto_now=True, verbose_name='时间'),
        ),
    ]
